const Homeproduct =
[
    {
        id: 1,
        Name: 'LG Vision35',
        price: '26000',
        image: 'image/p1.webp',
        cat: 'телевизор',
        type: 'new',
    },
    {
        id: 2,
        Name: 'Mac Book 2020 M1',
        price: '96000',
        image: 'image/p2.webp',
        cat: 'компьютер',
        type: 'new',
    },
    {
        id: 3,
        Name: 'Smart watch',
        price: '23600',
        image: 'image/p3.webp',
        cat: 'часы',
        type: 'new',
    },
    {
        id: 4,
        Name: 'ASUS 3090',
        price: '36800',
        image: 'image/p9.jpg',
        cat: 'компьютер',
        type: 'new',
    },
    {
        id: 5,
        Name: 'JBL Smart Talk',
        price: '98199',
        image: 'image/p4.webp',
        cat: 'колонка',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'Listener 523',
        price: '59990',
        image: 'image/p5.webp',
        cat: 'электроника',
        type: 'featured',
    },
    {
        id: 7,
        Name: 'Beats by Dre',
        price: '95600',
        image: 'image/p10.jpg',
        cat: 'наушники',
        type: 'featured',
    },
    {
        id: 8,
        Name: 'NaviSystem 96',
        price: '38900',
        image: 'image/p11.jpg',
        cat: 'электроника',
        type: 'featured',
    },
    {
        id: 9,
        Name: 'Iphone 13',
        price: '67000',
        image: 'image/p6.webp',
        cat: 'телефон',
        type: 'top',
    },
    {
        id: 10,
        Name: 'SoundLoud 360',
        price: '76600',
        image: 'image/p7.webp',
        cat: 'колонка',
        type: 'top',
    },
    {
        id: 11,
        Name: 'Marshall',
        price: '87789',
        image: 'image/p8.webp',
        cat: 'колонка',
        type: 'top',
    },
    {
        id: 12,
        Name: 'BigSpeaker 100',
        price: '80700',
        image: 'image/p12.jpg',
        cat: 'колонка',
        type: 'top',
    },
]
export default Homeproduct